config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    # Home page
    get("/", { to: "posts#index", as: "root" })

    get('edit_password/:id(.:format)', {to:'users#edit_password', as: 'edit_password'})
    post('update_password/:id(.:format)', {to:'users#update_password', as: 'update_password'})

    resources :posts do
    resources :comments, only: [:create, :destroy], shallow: true
    end

    resources :users
    resource :session, only: [:new, :destroy, :create]

    namespace :admin do 
      resources :dashboard, only: [:index]
    end


end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    validates(
        :email, 
        presence: true, 
        uniqueness: true,
        format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
      )

      # def change_password
      #   update_attribute :password, params[:user][:new_password]
      #   update_attribute :password_confirmation, params[:user],[:new_password_confirmation]
      # end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::ApplicationController
    def create
        user = User.new user_params
        if user.save
            session[:user_id] = user.id
            render json: {id: user.id}
        else
            render(
                json: {errors: user.errors.messages},
                status: 422
            )
        end
    end
   

    private
    def user_params
        user_params = params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :new, :create]
  before_action :find_user, only: [:edit, :update]
  before_action :authorize, only: [:edit, :update]


    def new
        @user = User.new
      end

      def show
        @user = User.find(params[:id])
      end
    
      def create
        @user = User.new user_params
        if @user.save
          session[:user_id] = @user.id
          flash[:primary] = "New user #{@user.name} created"
          redirect_to root_path
        else
          render :new
        end
      end

      def edit
        # @user = User.find(params[:id])
      end

      def update
        # @user = User.find(params[:id])
        # if can?([:edit, :update], @user)
          if @user.update(user_params)
          flash[:success] = "Profile updated"
          redirect_to @user
          else
            render 'edit'
        end
      end

      def edit_password
        @user = User.find(params[:id])
      end

      
      def update_password
       
        @user = User.find(params[:id])
     
        if (@user&.authenticate params[:current_password ]) && params[:current_password] != params[:password] && params[:password_confirmation] == params[:password]
            if @user.update password: params[:password] 
                flash[:success] = "Password updated"
                redirect_to user_path
            else
                flash[:danger] = @user.errors.full_messages.join(', ')
                redirect_to request.referrer
            end
        else
            flash[:danger] = "You've entered invalid password form inputs, Please follow rules"
            redirect_to request.referrer    
        end
    end




     

      
      private

      def find_user
        @user = User.find(params[:id])
      end
    
      def user_params
        params.require(:user).permit(
          :name,
          :email,
          :password,
          :password_confirmation,
        )
      end

      def authorize
        unless can?(:crud, @user)
          flash[:danger] = "Not Authorized"
          redirect_to root_path
        end
      end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<%= form_with model: @user, local: true do |form| %>
  <% if @user.errors.present? %>
    <p>
      <%= @user.errors.full_messages.join(", ") %>
    </p>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name,  class:"form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class:"form-control"  %>
  </div>
  <%= form.submit "Update Profile", class:"btn btn-outline-primary" %>
<% end %>

<div class="mt-4">
<%=link_to "Change Password", edit_password_path(@user),class:"btn btn-outline-primary" %>
</div>

app/views/users/edit_password.html.erb
<%= form_with url: update_password_path(@user), local: true do |form| %>
  <% if @user.errors.present? %>
    <p>
      <%= @user.errors.full_messages.join(", ") %>
    </p>
  <% end %>
  <div class="form-group">
    <%= form.label :current_Password%>
    <%= form.password_field :current_password, class:"form-control" , placeholder: "Your existing Password" %>
  </div>

 <div class="form-group">
    <%= form.label :new_password %>
    
    <%= form.password_field :password, class:"form-control", placeholder: "Must be different from Current Password" %>
  </div>
  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class:"form-control", placeholder: "Must be same as New Password" %>
  </div>
  <%= form.submit "Update Password", class:"btn btn-outline-primary"%>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user, local: true do |form| %>
  <% if @user.errors.present? %>
    <p>
      <%= @user.errors.full_messages.join(", ") %>
    </p>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control"  %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class:"form-control"  %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class:"form-control"  %>
  </div>
  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class:"form-control"  %>
  </div>
  <%= form.submit ("Sign Up"), class: "btn btn-outline-primary"%>
<% end %>

app/views/users/show.html.erb
<h2> <%= @user.name %> Profile Page</h2>



<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email</th>
  </tr>
  
    <tr>
      <td><%= @user.id %></td>
      <td><%= @user.name %></td>
      <td><%= @user.email %></td>
    </tr>
  
</table>