config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    # Home page
    get("/", { to: "posts#index", as: "root" })

    get('edit_password/:id(.:format)', {to:'users#edit_password', as: 'edit_password'})
    post('update_password/:id(.:format)', {to:'users#update_password', as: 'update_password'})

    resources :posts do
    resources :comments, only: [:create, :destroy], shallow: true
    end

    resources :users
    resource :session, only: [:new, :destroy, :create]

    namespace :admin do 
      resources :dashboard, only: [:index]
    end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <!DOCTYPE html>
<html>
  <head>
    <title>Blog On Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <!-- "link_to" is a method known as a view helper. Use it to generate an anchor tag -->
    <!-- <a href="/">Home</a> -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand text-primary" href="#">Blog On Rails</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: "nav-link text-primary" %>
          </li>
          <li class="nav-item">
            <%= link_to 'New Post', new_post_path, class: "nav-link text-primary" %>
          </li>
          <% if user_signed_in? %>
            
              <p class="nav-link mr-0">Welcome</p>
           
            <li class="nav-item ml-0">
                <%= link_to current_user.name.capitalize(), edit_user_path(current_user), class: "nav-link text-primary"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Out', session_path, method: :delete, data: {confirm: "Log out?" }, class: "nav-link text-primary" %>
            </li>
            <% if current_user.is_admin? %>
             <li class="nav-item">
              <%= link_to 'Dashboard', admin_dashboard_index_path, class: 'nav-link text-primary' %>
            </li> 
            <%end%>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign In', new_session_path, class: "nav-link text-primary" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_path, class: "nav-link text-primary" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container mt-3">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%=type %>" role="alert">
          <%= message %>
        </div>
      <% end %>
      
      <!-- yield will render the template of the current controller action -->
      <%= yield %>
    </div>
  </body>
</html>